### PR TITLE
Fixed Transform method of ResolveContentPropertyTransformer

### PR DESCRIPTION
**Pull request by ds1709**
* Added unit tests on `ResolveContentPropertyTransformer.Transform`.
* Fixed `ArgumentOutOfRangeException` (#109).

### CODE REVIEW

**Comment by ds1709** [comment]
I ran tests localy and it complete successfuly, so I don't understand why `Run tests` task fails in pipeline.

**Comment by MrJul** [comment]
> I ran tests localy and it complete successfuly, so I don't understand why `Run tests` task fails in pipeline.

You're using C# 12 collection expressions, but XamlX hasn't been updated to .NET 8 SDK yet.

Also, please add your tests to the existing `XamlParserTests` project instead of creating a new project - the files there are shared between several test projects, to allow the tests to run for both SRE (System.Reflection.Emit) and Cecil in several projects.

**Comment by ds1709** [comment]
I moved my tests in `XamlParserTests` project, and now I have problems with `PublikKey`s. Should I specify `PublikKey` in `InternalsVisibleTo` items or not? Also, `error CS0103: The name 'offender' does not exist in the current context` still persists (it's not my code).

**Comment by ds1709** [comment]
Well, seems like it's all OK now.

**Comment by ds1709** [comment]
Found critical error.

**Pull request closed without merging**
