### PR TITLE
Add support for nested types to CecilAssembly.

### LINKED ISSUE #2725: Support nested types in DataTemplate.DataType
Currently TypeResolver goes crazy - raises exception (for 0.8.x version [clarification: only for F# modules that don't have namespace]) and gives error in compile time from the master branch.

Just to show some sample. This kind of code is perfectly valid in WPF:

```xml
        <ItemsControl ItemsSource="{Binding Items}">
            <ItemsControl.ItemTemplate>
                <DataTemplate DataType="{x:Type local:SomeClass+Data}">
                    <TextBlock Text="{Binding Value}" />
                </DataTemplate>
            </ItemsControl.ItemTemplate>
        </ItemsControl>
```

```csharp
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            DataContext = this;
        }

        public IEnumerable<Data> Items { get => Enumerable.Range(0, 10).Select(_ => new Data()); }
    }

    public static class SomeClass
    {
        public class Data
        {
            public string Value { get; } = "Hello World";
        }
    }
```

While this is a rare use-case for C# in F# world it's common. Instead (or additional to) of using namespace, types are grouped in modules, like this:

```fs
module Test = 
    type SomeType = { Id : int; Value : string }
```

So I think it would be very nice to have support for this scenario.

### PR DESCRIPTION
**Pull request by grokys**
Adds support for nested types specified with a `+` to the Cecil backend.

Fixes https://github.com/AvaloniaUI/Avalonia/issues/2725.

### CODE REVIEW

**Comment by topeterk** [comment]
Hi @kekekeks , are there any issues with merging this change?
Or are you waiting for a rebase due to the github warning?

**Comment by hez2010** [comment]
Any updates?

**Comment by nuc134r** [comment]
This is essential feature for our localization system. All the localization consts are generated before build and accessed in XAML via nested static classes. Would be great to be able to use existing localization in Avalonia apps.

**Comment by nuc134r** [comment]
For everyone stumbling upon this – I have a workaround for `x:Static`

https://github.com/AvaloniaUI/Avalonia/issues/2725#issuecomment-1747346624

**Comment by workgroupengineering** [comment]
Can I continue the PR?

**Comment by kekekeks** [comment]
IIRC the original change was causing InvalidProgramException, which is why it wasn't merged.

**Comment by workgroupengineering** [comment]
> IIRC the original change was causing InvalidProgramException, which is why it wasn't merged.

Do you have a test that simulates the Exception? I tested the PR in the Sandbox of this [branch](https://github.com/workgroupengineering/Avalonia/tree/features/Core/Nested-Types) and it seems to work as I expected.

**Pull request closed without merging**
