### PR TITLE
Rename and refactor for XamlX structure and layering.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Rename XamlIL -> XamlX. Refactor out base classes for the compilers for 3 built-in compiler types, declarative, imperative, and IL (each builds on previous). Make the backend generic on the "raw" emitter and the result type returned by the node emitters.

Keep support for implementing emit for specific backends on the node types themselves while also supporting using emitter objects exclusively.

Contributes to #8.

Targets the history-rewritten xamlx-rename branch. Superscedes #10 

cc: @kekekeks

### CODE REVIEW

**Comment by kekekeks** [comment]
Why are we removing the 'X' postfix? Originally it was intended to differentiate between XAML engines. I'd rather avoid name clashes between `IXamlXType` and [IXamlType](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.markup.ixamltype). It's compiler internal anyway, so we don't have to worry about the XAML engine name leaking to the user-facing API.

It also seems to be a plain find/replace since it affects even xmlns urls and benchmark names.

**Comment by jkoritzinsky** [comment]
My thought was that we already have namespaces differentiating the types so we don’t need to also differentiate the type in the name.

**Comment by kekekeks** [comment]
Another `git filter-branch` it is then. I'll do a script to rename each type individually, I think.

**Comment by kekekeks** [comment]
Branch with updated history rewrite is here - https://github.com/kekekeks/XamlIl/tree/xamlx-rename2

I don't think we need to rename anything else.

You can find your current PR rebased on top of that branch in [this commit](https://github.com/kekekeks/XamlIl/commit/b6dd7a7035fcb32c0e2e5c3a502483c495df5c4f) (cherry-pick it or something).

**Comment by kekekeks** [comment]
Also, the current PR doesn't build because  ILEmitContext doesn't implement LoadLocalValue.

**Comment by kekekeks** [comment]
Also, `!= default` no longer works with generic type parameters in C# 9.

**Pull request closed without merging**
